src/CatalogMVC/CatalogInfrastructure/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CatalogDomain.Model;

namespace CatalogInfrastructure.Controllers
{
    public class ActorsController : Controller
    {
        private readonly DbCatalogContext _context;

        public ActorsController(DbCatalogContext context)
        {
            _context = context;
        }

        // GET: Actors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Actors.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!ModelState.IsValid)
            {
                return View(await _context.Actors.ToListAsync());
            }

            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                    .FirstOrDefaultAsync(m => m.Id == id);

            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Nationality,Id")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!ModelState.IsValid)
            {
                return View(await _context.Actors.ToListAsync());
            }

            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors.FindAsync(id);

            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Nationality,Id")] Actor actor)
        {
            if (id != actor.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(actor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!ModelState.IsValid)
            {
                return View(await _context.Actors.ToListAsync());
            }

            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.Id == id);

            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);

            //here should be some deleting code...
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!ModelState.IsValid)
            {
                return View(await _context.Actors.ToListAsync());
            }

            var actor = await _context.Actors.FindAsync(id);

            if (actor != null)
            {
                _context.Actors.Remove(actor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
            return _context.Actors.Any(e => e.Id == id);
        }
    }
}

src/CatalogMVC/CatalogInfrastructure/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CatalogDomain.Model;

namespace CatalogInfrastructure.Controllers
{
    public class GenresController : Controller
    {
        private readonly DbCatalogContext _context;

        public GenresController(DbCatalogContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Genres.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GenreName,Id")] Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GenreName,Id")] Genre genre)
        {
            if (id != genre.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.Id == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var genre = await _context.Genres.FindAsync(id);
            if (genre != null)
            {
                _context.Genres.Remove(genre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
            return _context.Genres.Any(e => e.Id == id);
        }
    }
}

src/CatalogMVC/CatalogInfrastructure/Controllers/QueriesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol.Plugins;
using System;
using CatalogDomain.Model;

namespace CatalogInfrastructure.Controllers
{
    public class QueriesController : Controller
    {
        private readonly DbCatalogContext _context;

        public QueriesController(DbCatalogContext context)
        {
            _context = context;
        }


        [HttpGet]
        public IActionResult SearchByGenre()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SearchByGenre(string genreName)
        {
            var result = await _context.Movies
                .FromSqlRaw(@"
                SELECT m.* 
                FROM Movie m
                JOIN MovieGenre mg ON m.Id = mg.MovieID
                JOIN Genre g ON g.Id = mg.GenreID
                WHERE g.GenreName = {0}", genreName)
                .ToListAsync();

            return View("~/Views/Home/Index.cshtml", result);
        }

        [HttpPost]
        public async Task<IActionResult> SearchByDirector(string directorLastName)
        {
            var result = await _context.Movies
                .FromSqlRaw(@"
                SELECT m.*
                FROM Movie m
                JOIN DirectedBy db ON m.Id = db.MovieId
                JOIN Director d ON d.Id = db.DirectorId
                WHERE d.LastName = {0}", directorLastName)
                .ToListAsync();

            return View("~/Views/Home/Index.cshtml", result);
        }

        [HttpPost]
        public async Task<IActionResult> SearchByActor(string actorLastName)
        {

            var result = await _context.Movies
                .FromSqlRaw(@"
                SELECT DISTINCT m.*
                FROM Movie m
                JOIN MovieCast mc ON m.Id = mc.MovieId
                JOIN Actor a ON a.Id = mc.ActorId
                WHERE a.LastName = {0}", actorLastName)
                .ToListAsync();

            return View("~/Views/Home/Index.cshtml", result);
        }

        [HttpPost]
        public async Task<IActionResult> SearchActorsByMinMovies(int minCount)
        {
            if (minCount <= 0)
            {
                ViewBag.AllGenreDirectors = null;
                return View("~/Views/Home/Index.cshtml");
            }

            var result = await _context.Actors
                .FromSqlRaw(@"
                SELECT a.*
                FROM Actor a
                JOIN MovieCast mc ON a.Id = mc.ActorId
                GROUP BY a.Id, a.FirstName, a.LastName, a.Nationality
                HAVING COUNT(mc.MovieId) > {0}", minCount)
                .ToListAsync();

            ViewBag.ActorResults = result;
            return View("~/Views/Home/Index.cshtml");
        }


        [HttpPost]
        public async Task<IActionResult> SearchDirectorsByMinMovies(int minCount)
        {
            if (minCount <= 0)
            {
                ViewBag.AllGenreDirectors = null;
                return View("~/Views/Home/Index.cshtml");
            }

            var result = await _context.Directors
                .FromSqlRaw(@"
                SELECT d.*
                FROM Director d
                JOIN DirectedBy db ON d.Id = db.DirectorId
                GROUP BY d.Id, d.FirstName, d.LastName, d.Nationality
                HAVING COUNT(db.MovieId) > {0}", minCount)
                .ToListAsync();

            ViewBag.DirectorResults = result;
            return View("~/Views/Home/Index.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> ActorsWithSameMovies(string actorLastName)
        {
            if (string.IsNullOrWhiteSpace(actorLastName))
            {
                ViewBag.SameMovieActors = null;
                return View("~/Views/Home/Index.cshtml");
            }

            var result = await _context.Actors
                .FromSqlRaw(@"
            SELECT a2.*
            FROM Actor a2
            WHERE a2.Id != (
                SELECT a1.Id
                FROM Actor a1
                WHERE a1.LastName = {0}
            )
            AND NOT EXISTS (
                SELECT *
                FROM MovieCast mc1
                WHERE mc1.ActorId = (
                    SELECT a1.Id FROM Actor a1 WHERE a1.LastName = {0}
                )
                AND NOT EXISTS (
                    SELECT *
                    FROM MovieCast mc2
                    WHERE mc2.ActorId = a2.Id AND mc2.MovieId = mc1.MovieId
                )
            )
            AND NOT EXISTS (
                SELECT *
                FROM MovieCast mc2
                WHERE mc2.ActorId = a2.Id
                AND NOT EXISTS (
                    SELECT *
                    FROM MovieCast mc1
                    WHERE mc1.ActorId = (
                        SELECT a1.Id FROM Actor a1 WHERE a1.LastName = {0}
                    )
                    AND mc1.MovieId = mc2.MovieId
                )
            )", actorLastName)
                .ToListAsync();

            ViewBag.SameMovieActors = result;
            return View("~/Views/Home/Index.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> DirectorsOfAllMoviesByGenre(string genreName)
        {
            if (string.IsNullOrWhiteSpace(genreName))
            {
                ViewBag.AllGenreDirectors = null;
                return View("~/Views/Home/Index.cshtml");
            }

            var result = await _context.Directors
                .FromSqlRaw(@"
            SELECT d.*
            FROM Director d
            WHERE NOT EXISTS (
                SELECT m.Id
                FROM Movie m
                JOIN MovieGenre mg ON m.Id = mg.MovieId
                JOIN Genre g ON g.Id = mg.GenreId
                WHERE g.GenreName = {0}
                AND NOT EXISTS (
                    SELECT *
                    FROM DirectedBy db
                    WHERE db.DirectorId = d.Id AND db.MovieId = m.Id
                )
            )", genreName)
                .ToListAsync();

            ViewBag.AllGenreDirectors = result;
            return View("~/Views/Home/Index.cshtml");
        }

        [HttpPost]
        public async Task<IActionResult> ActorsWithIdenticalFilmography()
        {
            var result = await _context.ActorPairs
                .FromSqlRaw(@"
            SELECT 
                a1.Id AS Actor1Id, a2.Id AS Actor2Id, 
                a1.FirstName AS Actor1FirstName, a1.LastName AS Actor1LastName,
                a2.FirstName AS Actor2FirstName, a2.LastName AS Actor2LastName,
                STRING_AGG(m.Title, ', ') AS Movies
            FROM Actor a1
            JOIN Actor a2 ON a1.Id < a2.Id
            JOIN MovieCast mc1 ON a1.Id = mc1.ActorId
            JOIN MovieCast mc2 ON a2.Id = mc2.ActorId AND mc1.MovieId = mc2.MovieId
            JOIN Movie m ON m.Id = mc1.MovieId
            WHERE NOT EXISTS (
                SELECT *
                FROM MovieCast mca
                WHERE mca.ActorId = a1.Id
                AND NOT EXISTS (
                    SELECT *
                    FROM MovieCast mcb
                    WHERE mcb.ActorId = a2.Id AND mcb.MovieId = mca.MovieId
                )
            )
            AND NOT EXISTS (
                SELECT *
                FROM MovieCast mcb
                WHERE mcb.ActorId = a2.Id
                AND NOT EXISTS (
                    SELECT *
                    FROM MovieCast mca
                    WHERE mca.ActorId = a1.Id AND mca.MovieId = mcb.MovieId
                )
            )
            GROUP BY 
                a1.Id, a2.Id, 
                a1.FirstName, a1.LastName, 
                a2.FirstName, a2.LastName
        ").ToListAsync();

            ViewBag.ActorPairs = result;
            return View("~/Views/Home/Index.cshtml");
        }


    }
}

src/CatalogMVC/CatalogInfrastructure/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h1>Меню лабораторної</h1>
<ul>
    <li><a asp-controller="Movies" asp-action="Index">Фільми</a></li>
    <li><a asp-controller="Directors" asp-action="Index">Режисери</a></li>
    <li><a asp-controller="Actors" asp-action="Index">Актори</a></li>
    <li><a asp-controller="Genres" asp-action="Index">Жанри</a></li>
</ul>


<h3>1. Фільми за жанром</h3>
<label for="genreName">Введіть назву жанру:</label>
<form asp-controller="Queries" asp-action="SearchByGenre" method="post"  style="display: flex; gap: 10px;">
    <input type="text" name="genreName" id="genreName" class="form-control w-50" placeholder="Назва жанру" />
    <button type="submit" class="btn btn-primary">Пошук</button>
</form>
<br />

<h3>2. Фільми за режисером</h3>
<label for="directorLastName">Введіть фамілію режисера:</label>
<form asp-controller="Queries" asp-action="SearchByDirector" method="post" style="display: flex; gap: 10px; margin-bottom: 20px;">
    <input type="text" name="directorLastName" class="form-control w-50" placeholder="Прізвище режисера" />
    <button type="submit" class="btn btn-primary">Пошук</button>
</form>
<br />

<h3>3. Фільми за актором</h3>
<label for="actorLastName">Введіть фамілію актора:</label>
<form asp-controller="Queries" asp-action="SearchByActor" method="post" style="display: flex; gap: 10px; margin-bottom: 20px;">
    <input type="text" name="actorLastName" class="form-control w-50" placeholder="Прізвище актора" />
    <button type="submit" class="btn btn-primary">Пошук</button>
</form>
<br />

<h3>4. Актори, які знімались більше ніж у X фільмах</h3>
<label for="minCount">Введіть число X:</label>
<form asp-controller="Queries" asp-action="SearchActorsByMinMovies" method="post" style="display: flex; gap: 10px; margin-bottom: 20px;">
    <input type="number" name="minCount" class="form-control w-50" placeholder="Мінімум фільмів" />
    <button type="submit" class="btn btn-primary">Пошук</button>
</form>
<br />

<h2>5. Режисери, які зрежисерували більше ніж X фільмів</h2>
<label for="minCount">Введіть число X:</label>
<form asp-controller="Queries" asp-action="SearchDirectorsByMinMovies" method="post" style="display: flex; gap: 10px; margin-bottom: 20px;">
    <input type="number" name="minCount" class="form-control w-50" placeholder="Мінімум фільмів" />
    <button type="submit" class="btn btn-primary">Пошук</button>
</form>
<br />

<h2>6. Актори, які знімались у тих самих фільмах, що і заданий актор</h2>
<label for="actorLastName">Введіть фамілію актора:</label>
<form asp-controller="Queries" asp-action="ActorsWithSameMovies" method="post" style="display: flex; gap: 10px; margin-bottom: 20px;">
    <input type="text" name="actorLastName" class="form-control w-50" placeholder="Прізвище актора" />
    <button type="submit" class="btn btn-primary">Пошук</button>
</form>
<br />

<h2>7. Режисери, які зрежисерували всі фільми жанру</h2>
<label for="genreName">Введіть назву жанру:</label>
<form asp-controller="Queries" asp-action="DirectorsOfAllMoviesByGenre" method="post" style="display: flex; gap: 10px; margin-bottom: 20px;">
    <input type="text" name="genreName" class="form-control w-50"  placeholder="Назва жанру" />
    <button type="submit" class="btn btn-primary">Пошук</button>
</form>
<br />

<h2>8. Пари акторів, які мають ідентичну фільмографію</h2>
<form asp-controller="Queries" asp-action="ActorsWithIdenticalFilmography" method="post">
    <button type="submit" class="btn btn-primary">Пошук</button>
</form>



@if (Model != null)
{
    if (Model.Count == 0)
    {
        <p>Нічого не знайдено.</p>
    }
    else
    {
        <h3>Результати:</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Назва фільму</th>
                    <th>Рік</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var movie in Model)
                {
                    <tr>
                        <td>@movie.Title</td>
                        <td>@movie.Year</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}


@if (ViewBag.ActorResults != null)
{
    var actors = (List<CatalogDomain.Model.Actor>)ViewBag.ActorResults;

    if (!actors.Any())
    {
        <p>Нічого не знайдено серед акторів.</p>
    }
    else
    {
        <h3>Актори:</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Ім’я</th>
                    <th>Прізвище</th>
                    <th>Національність</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var actor in actors)
                {
                    <tr>
                        <td>@actor.FirstName</td>
                        <td>@actor.LastName</td>
                        <td>@actor.Nationality</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

@if (ViewBag.DirectorResults != null)
{
    var directors = (List<CatalogDomain.Model.Director>)ViewBag.DirectorResults;

    if (!directors.Any())
    {
        <p>Нічого не знайдено серед режисерів.</p>
    }
    else
    {
        <h3>Режисери:</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Ім’я</th>
                    <th>Прізвище</th>
                    <td>Національність</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var director in directors)
                {
                    <tr>
                        <td>@director.FirstName</td>
                        <td>@director.LastName</td>
                        <td>@director.Nationality</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

@if (ViewBag.SameMovieActors != null)
{
    var actors = (List<CatalogDomain.Model.Actor>)ViewBag.SameMovieActors;

    if (!actors.Any())
    {
        <p>Немає акторів із такою ж фільмографією.</p>
    }
    else
    {
        <h3>Актори з такою ж фільмографією:</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Ім’я</th>
                    <th>Прізвище</th>
                    <th>Національність</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var actor in actors)
                {
                    <tr>
                        <td>@actor.FirstName</td>
                        <td>@actor.LastName</td>
                        <td>@actor.Nationality</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

@if (ViewBag.AllGenreDirectors != null)
{
    var directors = (List<CatalogDomain.Model.Director>)ViewBag.AllGenreDirectors;

    if (!directors.Any())
    {
        <p>Немає режисерів, які зрежисерували всі фільми жанру.</p>
    }
    else
    {
        <h3>Режисери, які зрежисерували всі фільми жанру:</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Ім’я</th>
                    <th>Прізвище</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var director in directors)
                {
                    <tr>
                        <td>@director.FirstName</td>
                        <td>@director.LastName</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

@if (ViewBag.ActorPairs != null)
{
    var pairs = (List<CatalogDomain.Model.ActorPair>)ViewBag.ActorPairs;

    if (!pairs.Any())
    {
        <p>Немає пар акторів з однаковою фільмографією.</p>
    }
    else
    {
        <h3>Пари акторів з однаковою фільмографією:</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Актор 1</th>
                    <th>Актор 2</th>
                    <th>Спільні фільми</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var pair in pairs)
                {
                    <tr>
                        <td>@pair.Actor1FirstName @pair.Actor1LastName</td>
                        <td>@pair.Actor2FirstName @pair.Actor2LastName</td>
                        <td>@pair.Movies</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}